export const theme = {
  color: {
    primary: "#27AE60",
    secondary: "#205FCE",
    dark: "#0E0E2C",
    text: "#4A4A68",
    subtle: "#5D5D5D",
    accent: "#ECF1F4",
    light: "#FAFCFE",
    white: "#fff",
    success: "#31D0AA",
    error: "#EA2B2B",
  },
  text: {
    h1: {
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "64px",
      lineHeight: "75px",
      letterSpacing: "-0.02em",
      textTransform: "capitalize",
      color: "#4A4A68",
    },
    h2: {
      color: "#4A4A68",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "40px",
      lineHeight: "47px",
      letterSpacing: "-0.02em",
      textTransform: "capitalize",
    },
    h3: {
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "24px",
      lineHeight: "28px",
      letterSpacing: "-0.02em",
      textTransform: "capitalize",
      color: "#4A4A68",
    },
    body: {
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "16px",
      lineHeight: "140%",
      letterSpacing: "-0.02em",
      color: "#4A4A68",
    },
    bold: {
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "16px",
      lineHeight: "19px",
      color: "#4A4A68",
    },
    small: {
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "14px",
      lineHeight: "140%",
      color: "#4A4A68",
    },
    preTitle: {
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "12px",
      lineHeight: "14px",
      letterSpacing: "-0.03em",
      textTransform: "uppercase",
      color: "#4A4A68",
    },
    button: {
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "16px",
      lineHeight: "19px",
      letterSpacing: "-0.04em",
      textTransform: "uppercase",
    },
    link: {
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "16px",
      lineHeight: "19px",
      textDecorationLine: "underline",
      color: "#4A4A68",
    },
  },
}
